### ISSUE TITLE
Text field parsing

### ISSUE THREAD

**Issue by TheGLander** [ChipMcCallahan/CCTools#1]
In both DAT and C2M parsers, text fields are treated as if they're encoded in UTF-8, while in actuality they're encoded in Latin-1. This causes the library to break when there are non-ASCII characters anywhere in a level's data.

**Comment by ChipMcCallahan** [comment]
Thanks for the report! I think this should fix, please LMK if it doesn't.

https://github.com/ChipMcCallahan/CCTools/commit/c9ed34675f41100938c10370956129b7acabc1de
