### ISSUE TITLE
Incompatible DAT output with CCEdit

### ISSUE THREAD

**Issue by TheGLander** [ChipMcCallahan/CCTools#2]
Currently, CCTools outputs DAT files which are incompatible with [CCEdit](https://github.com/zrax/cctools). This is because CCTools emits DAT files with the map detail set to 0, which CCEdit doesn't like. I've submitted [a pull request](https://github.com/zrax/cctools/pull/30) on the CCEdit repository so that files generated by this library work, but I imagine a quick fix would be just to write files with map detail set to 1.

**Comment by ChipMcCallahan** [comment]
Should be fixed with https://github.com/ChipMcCallahan/CCTools/commit/d053d2d19b1cd279f5e3a921da02fb977604a4fd
